theme: jekyll-theme-cayman
title: 乐者必成ROM
show_downloads: true
markdown: redcarpet
github:
  zip_url: https://service-5pbou4lr-1257232761.sh.apigw.tencentcs.com/release/Ali/
redcarpet:
    extensions: ["tables"]
